### PR TITLE
Revert "Arabic Omelette"

### PR DESCRIPTION
**Pull request by m4v15**
Reverts foundersandcoders/nazareth-recipes#46

### CODE REVIEW

**Comment by Karyum** [comment]
mate why ?

**Comment by Karyum** [comment]
@m4v15 that does not make any sense whats the reasoning behind this ?

**Comment by m4v15** [comment]
Can't merge your own PR mate, it's madness! 🙃

**Comment by Karyum** [comment]
@m4v15 
# That is stated no where

**Pull request merged**
