### PR TITLE
Arabic omellete

### LINKED ISSUE #8: Arabic Omelette

### PR DESCRIPTION
**Pull request by Karyum**
close #8 

Only giving the chance to @finnhodgkin and @matthewdking to be able to merge cause @m4v15 is controversial right now

### CODE REVIEW

**Comment by m4v15** [comment]
I'm glad you've come to your senses. However I would point out you need 3 reviewers including a maintainer - are you suggesting one of @matthewdking or @finnhodgkin get's promoted? We need a protocol for that ugh

**Comment by Karyum** [comment]
@m4v15 I mean i could say the same thing for you revert PR, it needed 3 reviewers and a maintainer. I'm not sure you are allowed in this PR anymore.

**Comment by shiryz** [comment]
@Karyum can we call it Mario's Omlette instead?

**Comment by Karyum** [comment]
@shiryz We could but that would just bloat my ego and then other people my see it and start doing the same

**Comment by shiryz** [comment]
Makes sense, but given that we haven't come to a consensus on what an arabic omlette is I call for an emergency naming convention

**Comment by Karyum** [comment]
@shiryz I say in my PR that i give the base of the Arabic omelette and said that people can get creative with it

**Review by matthewdking — APPROVED** [review]
Let's get this thing merged and all move on. Sorry @Karyum :heart:

**Review by finnhodgkin — APPROVED** [review]
LGTM :taco:

**Comment by finnhodgkin** [comment]
I reckon we give @Suuuuha / @mattlub until the end of the day to re-review and then hopefully get one of the maintainers to merge with or without approval... They can always request changes via issues at a later date. :+1: :heart:

**Pull request merged**
